version: '3.3'
services:
  wads:
    build: .
    hostname: wads
    #restart: unless-stopped
    volumes:
      - wadsvol:/usr/vol:rw
    image: innovanon/docker-wads:latest
    container_name: docker-wads

volumes:
  wadsvol:
    external: true

